# Generated by Django 5.2.1 on 2025-05-21 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=255)),
                ('sidlo_mesto', models.CharField(max_length=255)),
                ('sidlo_ulice', models.CharField(max_length=255)),
                ('sidlo_psc', models.CharField(max_length=255)),
                ('ico', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=255)),
                ('telefon', models.CharField(max_length=50)),
                ('fakturacni_nazev', models.CharField(blank=True, max_length=255, null=True)),
                ('fakturacni_mesto', models.CharField(blank=True, max_length=255, null=True)),
                ('fakturacni_ulice', models.CharField(blank=True, max_length=255, null=True)),
                ('fakturacni_psc', models.CharField(blank=True, max_length=255, null=True)),
                ('fakturacni_ico', models.CharField(blank=True, max_length=50, null=True)),
                ('fakturacni_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('fakturacni_telefon', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Klient',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sazba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hodnota', models.DecimalField(decimal_places=2, max_digits=18)),
                ('sazba_start', models.DateTimeField(db_column='SazbaStart')),
            ],
            options={
                'db_table': 'Sazba',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Subdodavatel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titul_pred', models.TextField(blank=True, null=True)),
                ('jmeno', models.TextField()),
                ('prijmeni', models.TextField()),
                ('titul_za', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Subdodavatel',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Subdodavka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.TextField()),
                ('aktivni', models.BooleanField()),
            ],
            options={
                'db_table': 'Subdodavka',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Zamestnanec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('jmeno', models.TextField()),
                ('prijmeni', models.TextField()),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'Zamestnanec',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='KlientPoznamka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateTimeField()),
                ('text', models.TextField()),
                ('klient', models.ForeignKey(db_column='KlientID', on_delete=django.db.models.deletion.CASCADE, to='zakazky.klient')),
            ],
            options={
                'db_table': 'KlientPoznamka',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Zakazka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zakazka_cislo', models.TextField(db_column='ZakazkaCislo')),
                ('nazev', models.TextField()),
                ('termin', models.DateTimeField()),
                ('zakazka_konec_predp', models.DateTimeField(blank=True, null=True)),
                ('zakazka_start', models.DateTimeField(blank=True, null=True)),
                ('zakazka_konec_skut', models.DateTimeField(blank=True, null=True)),
                ('predpokladany_cas', models.IntegerField()),
                ('mesto', models.TextField()),
                ('ulice', models.TextField()),
                ('psc', models.TextField()),
                ('orientacni_naklady', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('plna_moc', models.BooleanField()),
                ('hip', models.TextField()),
                ('popis_zadani', models.TextField()),
                ('klient', models.ForeignKey(db_column='ID_Klient', on_delete=django.db.models.deletion.CASCADE, to='zakazky.klient')),
                ('sazba', models.ForeignKey(blank=True, db_column='ID_Sazba', null=True, on_delete=django.db.models.deletion.SET_NULL, to='zakazky.sazba')),
            ],
            options={
                'db_table': 'Zakazka',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UredniZapis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popis', models.TextField()),
                ('datum', models.DateTimeField()),
                ('termin_do', models.DateTimeField(blank=True, null=True)),
                ('splneno', models.BooleanField()),
                ('zakazka', models.ForeignKey(db_column='ZakazkaId', on_delete=django.db.models.deletion.CASCADE, to='zakazky.zakazka')),
            ],
            options={
                'db_table': 'UredniZapis',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ZakazkaSubdodavka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cena', models.DecimalField(decimal_places=2, max_digits=18)),
                ('navyseni', models.DecimalField(decimal_places=2, max_digits=18)),
                ('fakturuje_klientovi', models.BooleanField()),
                ('fakturuje_arched', models.BooleanField()),
                ('subdodavatel', models.ForeignKey(db_column='ID_Subdodavatel', on_delete=django.db.models.deletion.DO_NOTHING, to='zakazky.subdodavatel')),
                ('subdodavka', models.ForeignKey(db_column='ID_Subdodavka', on_delete=django.db.models.deletion.DO_NOTHING, to='zakazky.subdodavka')),
                ('zakazka', models.ForeignKey(db_column='ID_Zakazka', on_delete=django.db.models.deletion.CASCADE, to='zakazky.zakazka')),
            ],
            options={
                'db_table': 'ZakazkaSubdodavka',
                'managed': True,
                'unique_together': {('zakazka', 'subdodavka', 'subdodavatel')},
            },
        ),
        migrations.CreateModel(
            name='ZakazkaZamestnanec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('den_prace', models.DateField(db_column='DenPrace')),
                ('cas_od', models.TimeField(blank=True, db_column='CasOd', null=True)),
                ('cas_do', models.TimeField(blank=True, db_column='CasDo', null=True)),
                ('popis', models.TextField(blank=True, null=True)),
                ('najete_km', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('zakazka', models.ForeignKey(db_column='ID_Zakazka', on_delete=django.db.models.deletion.CASCADE, to='zakazky.zakazka')),
                ('zamestnanec', models.ForeignKey(db_column='ID_Zamestnanec', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ZakazkaZamestnanec',
                'managed': True,
                'unique_together': {('zakazka', 'zamestnanec', 'den_prace')},
            },
        ),
        migrations.CreateModel(
            name='ZamestnanecZakazka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prideleno_hodin', models.IntegerField()),
                ('premie_predpoklad', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('premie_skutecnost', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('datum_prideleni', models.DateTimeField(blank=True, null=True)),
                ('popis', models.TextField(blank=True, null=True)),
                ('zakazka', models.ForeignKey(db_column='ID_Zakazka', on_delete=django.db.models.deletion.CASCADE, to='zakazky.zakazka')),
                ('zamestnanec', models.ForeignKey(db_column='ID_Zamestnanec', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ZamestnanecZakazka',
                'managed': True,
                'unique_together': {('zamestnanec', 'zakazka')},
            },
        ),
    ]
