# Generated by Django 5.2.1 on 2025-05-23 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakazky', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakazka',
            name='hip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='HIP'),
        ),
    ]
