# Generated by Django 5.2.1 on 2025-05-24 15:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakazky', '0002_alter_zakazka_hip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zamestnanec',
            options={},
        ),
        migrations.AddField(
            model_name='zamestnanec',
            name='datum_nastup',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='zamestnanec',
            name='sazba_hod',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zamestnanec',
            name='sazba_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='zamestnanec',
            name='titul',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='zamestnanec',
            name='jmeno',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='zamestnanec',
            name='prijmeni',
            field=models.CharField(max_length=255),
        ),
    ]
