# Generated by Django 5.2.1 on 2025-05-24 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakazky', '0003_alter_zamestnanec_options_zamestnanec_datum_nastup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zamestnaneczakazka',
            name='zakazka',
            field=models.ForeignKey(db_column='ID_Zakazka', on_delete=django.db.models.deletion.CASCADE, related_name='prirazeni', to='zakazky.zakazka'),
        ),
    ]
